FROM ethereum/client-go:alltools-stable

LABEL version="1.0"
LABEL maintainer="Promit.Chattterjee@gmail.com"

RUN apk add --update bash

WORKDIR /root

COPY ./common/genesis.json /root/.

RUN geth init /root/genesis.json

ENTRYPOINT bash
